### ISSUE TITLE
Error thrown is Function contains = in argument

### ISSUE THREAD

**Issue by demonmind** [lautis/uglifier#100]
I have a function in javascript that contains = sign in arguments such as the one below

```
function(arg1=null, arg2=null){
....
}
```
I get this error

`ExecJS::ProgramError: Unexpected token operator «=», expected punc «,»`

Any help would be appriciated

**Comment by lautis** [comment]
UglifyJS currently has very limited support for ES6. mishoo/UglifyJS2#448 contains more information about the status.

It probably would make sense to clarify that Uglifier is due to the underlying library also a ES5 minifier.

**Comment by demonmind** [comment]
Fixed this by not using uglifyer and switching to Closure
