### ISSUE TITLE
Missing mangle option in documentation

### ISSUE THREAD

**Issue by yivo** [lautis/uglifier#102]
For both the compressor and mangler there are separate `keep_fnames` options.

https://github.com/mishoo/UglifyJS2/issues/552#issuecomment-68931039

In README for Uglifier there is `keep_fnames` in `compress` section, but there is no in `mangle` section.

**Comment by lautis** [comment]
Thanks! Added that to documentation and also the global `keep_fnames` that implies both compress and mangle option.
