### ISSUE TITLE
Harmonize Uglifier

### ISSUE THREAD

**Issue by jhabdas** [lautis/uglifier#108]
I use this dependency as a part of Jekyll Assets Gem. But there are things I can't do with it right now because it has some issues uglifying ES6 files. Could you roll up a beta using https://github.com/mishoo/UglifyJS2/releases/tag/harmony-v2.7.5?

**Comment by lautis** [comment]
Released as 3.0.4.harmony1.

**Comment by jhabdas** [comment]
https://github.com/jekyll/jekyll-assets/issues/365#issuecomment-309334881

**Comment by jhabdas** [comment]
Mmm. Going to open a new ticket for this.
