### ISSUE TITLE
Support for input source maps which are inlined

### ISSUE THREAD

**Issue by yinghaochan** [lautis/uglifier#111]
bundlers such as webpack allow for source maps (and data) to be inlined into the JS file itself https://webpack.github.io/docs/configuration.html#devtool

would it be possible to support inlined source maps for input? 

Seems like https://github.com/lautis/uglifier/blob/master/spec/source_map_spec.rb#L97
supports input source maps, but only if the maps are in a separate file

**Comment by lautis** [comment]
This should be supported since 3.0: https://github.com/lautis/uglifier/blob/master/spec/source_map_spec.rb#L171

**Comment by yinghaochan** [comment]
ah, it wasn't working because I had an older version. Thanks!
