### ISSUE TITLE
Make Uglify ES the Default

### ISSUE THREAD

**Issue by jhabdas** [lautis/uglifier#119]
From #108, and using the ES2015 specification, I'd like to know what it would take to use ES6 version of the uglifier by default now.

**Comment by lautis** [comment]
Uglifier since 3.1.0 has the harmony version included, but not enabled by default. No need to install separate gem versions.

I'd like follow UglifyJS when to enable harmony mode by default. When UglifyJS releases harmony mode in their regular releases, it should be ready to use in Uglifier.

**Comment by jhabdas** [comment]
Sounds like a solid plan.
