### ISSUE TITLE
Incorrect options interpretation for `compress: false`

### ISSUE THREAD

**Issue by RKushnir** [lautis/uglifier#120]
Hi,
when initializing `Uglifier` with `compress: false`, it treats it as if you want to compress with default settings, instead of disabling the compression altogether.

I figured, it's caused by this line https://github.com/lautis/uglifier/blob/b183403ac741c8f6af16cd0bae0a61096cce1168/lib/uglifier.rb#L237
Given `compress: false` and no value for `:squeeze`, the expression `@options[:compress] || @options[:squeeze]` evaluates to `nil`, leading to usage of default settings.

An obvious workaround is to set `squeeze: false`.

**Comment by lautis** [comment]
Fixed in 76d42e85a2a2fef2a35e39354457c67e76f62d3f

**Comment by lautis** [comment]
Fixed in 4.0.0
