### ISSUE TITLE
ES6 for-of is not parsed correctly

### ISSUE THREAD

**Issue by joneslee85** [lautis/uglifier#126]
It seems to me ES6 `for-of` is not correctly parsed. 

```
Uglifier.new.compile("for (var value of myArray) { console.log(value) }")
# => Uglifier::Error: Unexpected token name «of», expected punc «;»
```

Wondering if others experience same issue.

**Comment by lautis** [comment]
ES6 support in uglifyjs is still more or less experimental and not enabled by default in Uglifier. `Uglifier.new(harmony: true).compile("for (var value of myArray) { console.log(value) }")` works.

**Comment by jtara** [comment]
Any thoughts about supporting uglify-es? I have not come across a Gem that wraps it yet...

**Comment by lautis** [comment]
Yes, you can use uglify-es. The option is named `harmony`, which is slightly inconvenient. At least I wasn't aware at the time that there would be a long-running separate package with name uglify-js at the time when that was added to Uglifier.

This should work:

```ruby
Uglifier.new(harmony: true).compile("for (var value of myArray) { console.log(value) }")
```
