### ISSUE TITLE
Uglifier::Error: Unexpected token: punc ((). To use ES6 syntax, harmony mode must be enabled with Uglifier.new(:harmony => true)

### ISSUE THREAD

**Issue by goldenstar999** [lautis/uglifier#127]
Hi, 
When I run "rake assets:precompile RAILS_ENV=production" command, I have issue.
 rake assets:precompile RAILS_ENV=production
rake aborted!
Uglifier::Error: Unexpected token: punc ((). To use ES6 syntax, harmony mode must be enabled with Uglifier.new(:harmony => true).
/Users/leonverspeek/.rvm/gems/ruby-2.3.1@zombie/gems/uglifier-4.0.2/lib/uglifier.rb:237:in `parse_result'
/Users/leonverspeek/.rvm/gems/ruby-2.3.1@zombie/gems/uglifier-4.0.2/lib/uglifier.rb:219:in `run_uglifyjs'
/Users/leonverspeek/.rvm/gems/ruby-2.3.1@zombie/gems/uglifier-4.0.2/lib/uglifier.rb:169:in `compile'
/Users/leonverspeek/.rvm/gems/ruby-2.3.1@zombie/gems/sprockets-3.7.1/lib/sprockets/uglifier_compressor.rb:53:in `call'
/Users/leonverspeek/.rvm/gems/ruby-2.3.1@zombie/gems/sprockets-3.7.1/lib/sprockets/uglifier_compressor.rb:28:in `call'
/Users/leonverspeek/.rvm/gems/ruby-2.3.1@zombie/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
/Users/leonverspeek/.rvm/gems/ruby-2.3.1@zombie/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/Users/leonverspeek/.rvm/gems/ruby-2.3.1@zombie/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/Users/leonverspeek/.rvm/gems/ruby-2.3.1@zombie/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
/Users/leonverspeek/.rvm/gems/ruby-2.3.1@zombie/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/Users/leonverspeek/.rvm/gems/ruby-2.3.1@zombie/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
/Users/leonverspeek/.rvm/gems/ruby-2.3.1@zombie/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/Users/leonverspeek/.rvm/gems/ruby-2.3.1@zombie/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
/Users/leonverspeek/.rvm/gems/ruby-2.3.1@zombie/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/Users/leonverspeek/.rvm/gems/ruby-2.3.1@zombie/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
/Users/leonverspeek/.rvm/gems/ruby-2.3.1@zombie/gems/sprockets-3.7.1/lib/sprockets/base.rb:66:in `find_asset'
/Users/leonverspeek/.rvm/gems/ruby-2.3.1@zombie/gems/sprockets-3.7.1/lib/sprockets/base.rb:73:in `find_all_linked_assets'
/Users/leonverspeek/.rvm/gems/ruby-2.3.1@zombie/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:142:in `block in find'
/Users/leonverspeek/.rvm/gems/ruby-2.3.1@zombie/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
/Users/leonverspeek/.rvm/gems/ruby-2.3.1@zombie/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:228:in `block in stat_tree'
/Users/leonverspeek/.rvm/gems/ruby-2.3.1@zombie/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:212:in `block in stat_directory'
/Users/leonverspeek/.rvm/gems/ruby-2.3.1@zombie/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `each'
/Users/leonverspeek/.rvm/gems/ruby-2.3.1@zombie/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `stat_directory'
/Users/leonverspeek/.rvm/gems/ruby-2.3.1@zombie/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:227:in `stat_tree'
/Users/leonverspeek/.rvm/gems/ruby-2.3.1@zombie/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:105:in `each'
/Users/leonverspeek/.rvm/gems/ruby-2.3.1@zombie/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:105:in `block in logical_paths'
/Users/leonverspeek/.rvm/gems/ruby-2.3.1@zombie/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:104:in `each'
/Users/leonverspeek/.rvm/gems/ruby-2.3.1@zombie/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:104:in `logical_paths'
/Users/leonverspeek/.rvm/gems/ruby-2.3.1@zombie/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:140:in `find'
/Users/leonverspeek/.rvm/gems/ruby-2.3.1@zombie/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:185:in `compile'
/Users/leonverspeek/.rvm/gems/ruby-2.3.1@zombie/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
/Users/leonverspeek/.rvm/gems/ruby-2.3.1@zombie/gems/sprockets-3.7.1/lib/rake/sprocketstask.rb:147:in `with_logger'
/Users/leonverspeek/.rvm/gems/ruby-2.3.1@zombie/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
/Users/leonverspeek/.rvm/gems/ruby-2.3.1@zombie/gems/rake-12.2.1/exe/rake:27:in `<top (required)>'
/Users/leonverspeek/.rvm/gems/ruby-2.3.1@zombie/bin/ruby_executable_hooks:15:in `eval'
/Users/leonverspeek/.rvm/gems/ruby-2.3.1@zombie/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)

How to fix this issue?

**Comment by abraham** [comment]
Try replacing

    config.assets.js_compressor = :uglifier

with

    config.assets.js_compressor = Uglifier.new(harmony: true)

in `config/environments/production.rb`

**Comment by chengs2416me** [comment]
abraham, you save my day

**Comment by FrancoisRab** [comment]
Thanks abraham !

**Comment by rgaufman** [comment]
Thank you, that worked! - Is there any reason why I wouldn't want to enable ES6 syntax or why this feature isn't on by default?

**Comment by lautis** [comment]
ES6 is not enabled in the master branch of UglifyJS. I've considered more or less beta, so it's not enabled by default.

**Comment by geminiyellow** [comment]
woo! amazing!

**Comment by AdnanTheExcellent** [comment]
I encountered this issue when upgrading to rails 5.2 (and a few other gems). However, I'm now getting this error when i update the js_compressor line (to  `config.assets.js_compressor = Uglifier.new(harmony: true)`) that @abraham suggested:

error:
`Sprockets::Error: unknown compressor: js_compressor`

stack trace:
```
rake aborted!
Sprockets::Error: unknown compressor: js_compressor
/home/nestmg6/.rvm/gems/ruby-2.5.1/gems/sprockets-3.7.2/lib/sprockets/compressing.rb:63:in `js_compressor='
/home/nestmg6/.rvm/gems/ruby-2.5.1/bundler/gems/requirejs-rails-1479da3c1c26/lib/tasks/requirejs-rails_tasks.rake:123:in `block (3 levels) in <top (required)>'
/home/nestmg6/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => requirejs:precompile:all => requirejs:precompile:digestify_and_compress => requirejs:precompile:run_rjs => requirejs:precompile:prepare_source
(See full trace by running task with --trace)
rake aborted!
Command failed with status (1): [/usr/local/rvm/rubies/ruby-2.5.1/bin/ruby ...]
/home/nestmg6/.rvm/gems/ruby-2.5.1/bundler/gems/requirejs-rails-1479da3c1c26/lib/tasks/requirejs-rails_tasks.rake:18:in `ruby_rake_task'
/home/nestmg6/.rvm/gems/ruby-2.5.1/bundler/gems/requirejs-rails-1479da3c1c26/lib/tasks/requirejs-rails_tasks.rake:83:in `block (3 levels) in <top (required)>'
/home/nestmg6/.rvm/gems/ruby-2.5.1/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/home/nestmg6/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
/home/nestmg6/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => assets:precompile => requirejs:precompile:external
```

Any idea why i'm getting this? I am using uglifier 4.1.14

**Comment by abraham** [comment]
@AdnanTheExcellent Looks like you are running into this https://github.com/jwhitley/requirejs-rails/pull/206

**Comment by crwhitesides** [comment]
Thank you!

**Comment by deepkum** [comment]
Repalced 
config.assets.js_compressor = :uglifier
with

config.assets.js_compressor = Uglifier.new(harmony: true)
in config/environments/production.rb

as suggested by @abraham abraham but i am encountering new error after this

**Comment by protigen34** [comment]
Hey, I updated uglifier to the latest version and I am seeing getting this error in the rake assets:precompile step while trying to push to heroku:
```ruby
remote:        Uglifier::Error: Unexpected token: string (ProductChannel)
```

How can I fix the issue?

**Comment by bnathan04** [comment]
After ensuring uglifier is the latest version, and following Abraham's step above, I still end up with the following error during the rake assets:precompile step while trying to push to heroku:

`remote:        Uglifier::Error: Unexpected token: operator (=)`

Any suggestions on how to get by this problem?

**Comment by NelcifranMagalhaes** [comment]
Nice...its save me @abraham XD

**Comment by felipepaifer** [comment]
Thank you!!!

**Comment by tommulliez** [comment]
> Repalced
> config.assets.js_compressor = :uglifier
> with
> 
> config.assets.js_compressor = Uglifier.new(harmony: true)
> in config/environments/production.rb
> 
> as suggested by @abraham abraham but i am encountering new error after this
> 
> Uglifier::Error: Unexpected token punc «;», expected punc «,»
> 
> I'v got the same issus : Uglifier::Error: Unexpected token: punc (:)
Do you fixed it finally ? Thank you :-)

**Comment by drcenterprises** [comment]
@abraham thanks i worked for me

**Comment by arefin-zeno** [comment]
> Try replacing
> 
> ```
> config.assets.js_compressor = :uglifier
> ```
> with
> 
> ```
> config.assets.js_compressor = Uglifier.new(harmony: true)
> ```
> in `config/environments/production.rb`

@abraham You are a superhero.

**Comment by dsignr** [comment]
> Try replacing
> 
> ```
> config.assets.js_compressor = :uglifier
> ```
> with
> 
> ```
> config.assets.js_compressor = Uglifier.new(harmony: true)
> ```
> in `config/environments/production.rb`

For some reason, this leads to:

```ruby
rake aborted!
NameError: uninitialized constant Uglifier
```

**Comment by dsignr** [comment]
> > Try replacing
> > ```
> > config.assets.js_compressor = :uglifier
> > ```
> > with
> > ```
> > config.assets.js_compressor = Uglifier.new(harmony: true)
> > ```
> > in `config/environments/production.rb`
> 
> For some reason, this leads to:
> 
> ```ruby
> rake aborted!
> NameError: uninitialized constant Uglifier
> ```

Nevermind, this was just a case of missing something as simple as 

`require 'uglifier'` in `production.rb`

Silly me.

**Comment by fwolfst** [comment]
Is there any way to figure out which source JS-file is the culprit? iiuc, the error happens while compressing javascript code, so in theory there should be a solution by cleaning up the code before compression, isnt it?

**Comment by humphreyja** [comment]
@fwolfst Just use a rake task.  This only checks the asset pipeline files.  You may also want to check your vendor file.  I had this issue and found out that eslint was converting a vendor file into es6 syntax.

```ruby
namespace :javascript do
  desc "Compiles each js file"
  task validate: :environment do
    JS_PATH = "app/assets/javascripts/**/*.js"
    Dir[JS_PATH].each do |file_name|
      puts "\n#{file_name}"
      puts Uglifier.compile(File.read(file_name))
    end
  end
end
```

**Comment by gsauzande** [comment]
I ran into this issue because Prettier was formatting an old jQuery file and adding ES6 syntax. Just throwing this solution in there in case someone gets stuck. Just save the file without Prettier.

**Comment by jwmount** [comment]
config.assets.js_compressor = Uglifier.new(harmony: true) didn't work for me, but I going up 3 release levels  from 1.X something it got a lot better.  Try going to '4.0.2'.

**Comment by hebergentilin** [comment]
> config.assets.js_compressor = Uglifier.new(harmony: true) didn't work for me, but I going up 3 release levels from 1.X something it got a lot better. Try going to '4.0.2'.

same error here

**Comment by akhildave** [comment]
I ran this commands on command line.

rails c
Uglifier.compile(File.read('app/assets/javascripts/messages.js'))

I got this error:

 Uglifier.compile(File.read('app/assets/javascripts/messages.js'));
Uglifier::Error: Unexpected token: punc ((). To use ES6 syntax, harmony mode must be enabled with Uglifier.new(:harmony => true).

How to fix this?
I opened up the page in browser which was using this messages.js file and found "Uncaught SyntaxError: Function statements require a function name" in **browser console.**

**Comment by paultursuru** [comment]
Hi, 
I'm facing the same situation here, everything is working great locally but then I have a problem during the precompiling when pushing to heroku.. 

> remote:        rake aborted!
remote:        Uglifier::Error: Unexpected token: string (actiontext). To use ES6 syntax, harmony mode must be enabled with Uglifier.new(:harmony => true).
remote:        --
remote:         => import "actiontext"
remote:         2 ;
remote:        ==

I did the "config.assets.js_compressor = Uglifier.new(harmony: true)" thing in production but here is what i get in the console : 

> irb(main):001:0> Uglifier.compile(File.read('app/javascript/packs/application.js'))
Traceback (most recent call last):
        1: from (irb):1
Uglifier::Error (Unexpected token: string (actiontext). To use ES6 syntax, harmony mode must be enabled with Uglifier.new(:harmony => true).)
--
 1 console.log('Hello World from Webpacker')
 2 
 => import "actiontext"
 4 
 5 require("@rails/actiontext")
 6 require("trix")
==

**Comment by ziaulrehman40** [comment]
Simply updating uglifier(from 4.1 to 4.2) lead us to actual place of error.

**Comment by jlurena** [comment]
We don't have ES6 syntax yet I get this error?

**Comment by AxelTheGerman** [comment]
In case anyone comes here looking for a solution to a similar error:

```
Uglifier::Error: Unexpected token: keyword (extends)        
--        
  1 import { Controller } from "stimulus"        
  2        
  => export default class extends Controller {
```

I recommend following [this solution](https://discuss.hotwire.dev/t/when-use-js-compressor-compile-stimulus-controller/2146/2) and switch to [terser-ruby](https://github.com/ahorek/terser-ruby)
