### ISSUE TITLE
Link to Uglifier changes on version bumps

### ISSUE THREAD

**Issue by chevinbrown** [lautis/uglifier#128]
Could you please at least link to uglifier changes on version bumps?

**Comment by lautis** [comment]
Possibly. Where should this link be and what it should contain or where it should point to?

**Comment by chevinbrown** [comment]
For example, the most recent changelog could read:

## 4.1.3 (7 January 2018)

- update UglifyJS to [3.3.5](https://github.com/mishoo/UglifyJS2/compare/v3.3.5...master)

You're at the mercy of mishoo, though, so it may be difficult given their releases. In any case, some people (like me) are very particular about gem changes and want to see the changes more easily than googling gem versions. 😺

**Comment by lautis** [comment]
Link to git commits could work, I’ll look into how easy it’d be to add those to the changelog script. 

An easy to digest changelog for UglifyJS sure would be nice for maintaining Uglifier too.

**Comment by chevinbrown** [comment]
Yes, I agree. Maybe this request can trickle down. 😉 Regardless, thanks for your work.
