### ISSUE TITLE
Error when using Javascript back-ticks for template literal

### ISSUE THREAD

**Issue by javinto** [lautis/uglifier#133]
When I use Javascript template literals for interpolation I get an Uglifier::Error. Example

```console.log(`This should match ${times} times`);```

I get the following error on deployment of my Rails application:

Uglifier::Error: Unexpected character '`'

.../bundle/ruby/2.4.0/gems/uglifier-4.1.8/lib/uglifier.rb:234:in `parse_result'

**Comment by opensourceame** [comment]
You need to change the parsing engine. Edit your `config/environment/production.rb` and look for the Uglifier line. Change it to:

`config.assets.js_compressor = Uglifier.new(harmony: true)`

**Comment by HansPalacios** [comment]
Ive been trying to launch to Heroku and first it says Precompiling assets failed, then when i try 
`RAILS_ENV=production bundle exec rake assets:precompile`
it responds with 
`yarn install v1.7.0
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.07s.
rake aborted!
Uglifier::Error: Unexpected character '#'
/Users/hans-sebastianpalacios/.rvm/gems/ruby-2.4.0/gems/uglifier-4.1.15/lib/uglifier.rb:234:in `parse_result'
/Users/hans-sebastianpalacios/.rvm/gems/ruby-2.4.0/gems/uglifier-4.1.15/lib/uglifier.rb:216:in `run_uglifyjs'
/Users/hans-sebastianpalacios/.rvm/gems/ruby-2.4.0/gems/uglifier-4.1.15/lib/uglifier.rb:168:in `compile'
/Users/hans-sebastianpalacios/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/uglifier_compressor.rb:53:in `call'
/Users/hans-sebastianpalacios/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/uglifier_compressor.rb:28:in `call'
/Users/hans-sebastianpalacios/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
/Users/hans-sebastianpalacios/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/Users/hans-sebastianpalacios/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/Users/hans-sebastianpalacios/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
/Users/hans-sebastianpalacios/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/Users/hans-sebastianpalacios/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'
/Users/hans-sebastianpalacios/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/Users/hans-sebastianpalacios/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'
/Users/hans-sebastianpalacios/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/Users/hans-sebastianpalacios/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'
/Users/hans-sebastianpalacios/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/base.rb:66:in `find_asset'
/Users/hans-sebastianpalacios/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/base.rb:73:in `find_all_linked_assets'
/Users/hans-sebastianpalacios/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:142:in `block in find'
/Users/hans-sebastianpalacios/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
/Users/hans-sebastianpalacios/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:228:in `block in stat_tree'
/Users/hans-sebastianpalacios/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:212:in `block in stat_directory'
/Users/hans-sebastianpalacios/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:209:in `each'
/Users/hans-sebastianpalacios/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:209:in `stat_directory'
/Users/hans-sebastianpalacios/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:227:in `stat_tree'
/Users/hans-sebastianpalacios/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:105:in `each'
/Users/hans-sebastianpalacios/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:105:in `block in logical_paths'
/Users/hans-sebastianpalacios/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:104:in `each'
/Users/hans-sebastianpalacios/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:104:in `logical_paths'
/Users/hans-sebastianpalacios/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:140:in `find'
/Users/hans-sebastianpalacios/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:186:in `compile'
/Users/hans-sebastianpalacios/.rvm/gems/ruby-2.4.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
/Users/hans-sebastianpalacios/.rvm/gems/ruby-2.4.0/gems/sprockets-3.7.2/lib/rake/sprocketstask.rb:147:in `with_logger'
/Users/hans-sebastianpalacios/.rvm/gems/ruby-2.4.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
/Users/hans-sebastianpalacios/.rvm/gems/ruby-2.4.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/Users/hans-sebastianpalacios/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
/Users/hans-sebastianpalacios/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
`

**Comment by HansPalacios** [comment]
Ive been trying to launch to Heroku and first it says Precompiling assets failed, then when i try

`RAILS_ENV=production bundle exec rake assets:precompile`

it responds with

`yarn install v1.7.0

[1/4] 🔍  Resolving packages...

success Already up-to-date.

✨  Done in 0.07s.

rake aborted!

Uglifier::Error: Unexpected character '#'
`

**Comment by juansecaro** [comment]
> You need to change the parsing engine. Edit your `config/environment/production.rb` and look for the Uglifier line. Change it to:
> 
> `config.assets.js_compressor = Uglifier.new(harmony: true)`
> 
> see:
> 
> https://github.com/lautis/uglifier#rails

Thanks! That did the work

**Comment by tylerbeckert** [comment]
> You need to change the parsing engine. Edit your `config/environment/production.rb` and look for the Uglifier line. Change it to:
> 
> `config.assets.js_compressor = Uglifier.new(harmony: true)`
> 
> see:
> 
> https://github.com/lautis/uglifier#rails

This resolved the issue for me too 👍🏻

**Comment by javinto** [comment]
Thank you, just tested with config.assets.js_compressor = Uglifier.new(harmony: true) and that solved the problem.
