### ISSUE TITLE
Uglifier gem 4.1.19 + UglifyJS 3.4.9 has a bug

### ISSUE THREAD

**Issue by pedrofurtado** [lautis/uglifier#155]
@lautis Just for notice: The version 4.1.19 of Uglifier gem uses the version 3.4.9 of UglifyJS. This version of UglifyJS has a bug that can affect order of execution code. Here is a link to some issues reporting this:

https://github.com/mishoo/UglifyJS2/issues/3278
https://github.com/mishoo/UglifyJS2/issues/3288
https://github.com/alexlamsl/UglifyJS2/commit/2bdaca10ae05136843d8e99da50925091a593373#comments
https://github.com/mishoo/UglifyJS2/issues/3271

Anyway, when a patch be provided by UglifyJS, it is important to upgrade the gem to get the new latest (and fixed) version of UglifyJS (possibly 3.4.10 or something like that).

For users getting trouble with this, subscribe the issue above.

Thanks! 👍

**Comment by lautis** [comment]
I'll definitely update once there is an update. Perhaps it would make sense to release 4.1.20 with UglifyJS 3.4.8 as that seems to be better.

Alternatively, I could look into switching to [terser](https://github.com/terser-js/terser) as the backend.

**Comment by pedrofurtado** [comment]
@lautis Thanks for feedback! I created the issue to help other users that could have some trouble with this, while the UglifyJS team does not release a minor version fixing this bug.

**Comment by pedrofurtado** [comment]
For a while, there are two workarounds:

1 - Lock the version of Uglifier gem to 4.1.18
2 - Maintain the version of Uglifier gem to 4.1.19, but configure the "conditionals" optimization to false

**Comment by lautis** [comment]
@pedrofurtado how about if Uglifier changed the default value for conditionals to false?

**Comment by pedrofurtado** [comment]
@lautis This could be also a good workaround 👍  Just let me test here if changing this the bug is fixed. If so, I tell you and a new version of gem (setting this option to false) can be released.

**Comment by pedrofurtado** [comment]
I comment here in a few minutes 🤝

**Comment by nylen** [comment]
Pinning UglifyJS to 3.4.8 would also fix this issue.

Releasing a new version and then disappearing is bad form.

**Comment by pedrofurtado** [comment]
@lautis Thanks, man! I updated here to version 4.1.20 of gem 👍
