### ISSUE TITLE
Different versions between `VERSION` and published

### ISSUE THREAD

**Issue by ybiquitous** [lautis/uglifier#169]
Hi, I noticed that the current `Uglifier::VERSION` (`4.1.20`) is different from the version (`4.2.0`) published to RubyGems.org.

https://github.com/lautis/uglifier/blob/ac86e3ea64243ad3e2ab5c909b54725b0d712716/lib/uglifier/version.rb#L3

https://rubygems.org/gems/uglifier/versions/4.2.0

Will the issue be fixed soon, or is it no matter?

**Comment by lautis** [comment]
Sorry, I forgot to push the version bump to GitHub. This is now fixed.

**Comment by ybiquitous** [comment]
Thank you! 😆
