### ISSUE TITLE
How to keep the sourceMapUrl in the source file?

### ISSUE THREAD

**Issue by volkanunsal** [lautis/uglifier#79]
I am using webpack to generate the source map before running the files through the Uglifier. I understand the default behavior is to always remove the comments at the end of a file, even when they match the pattern in `comments: Regexp` option. Is there a way around this?

**Comment by lautis** [comment]
It seems that UglifyJS removes all trailing comments regardless of comment preservation options. Likely the comments are already missing when producing the minified code.

In this particular case, wouldn't you want to use the sourceMapUrl comment as input for Uglifer? Ideally, Uglifier should do this automatically, but you could parse sourceMapUrl from the script and give it as `: input_source_map`. `:source_map_url` parameter can be used to append a new sourceMapUrl in the output, but using the original value might not be valid after running Uglifer.

**Comment by volkanunsal** [comment]
Thank you. I ended up bypassing Sprockets to minify from Webpack.
