### ISSUE TITLE
Weird output

### ISSUE THREAD

**Issue by jcuenod** [lautis/uglifier#82]
At the end of my uglified js on heroku, I have:

    /* ... actual code */}.call(this),function(){}.call(this),function(){}.call(this),function(){}.call(this),function(){}.call(this),function(){}.call(this);

I must be honest, I'm not sure how to begin debugging this.

**Comment by lautis** [comment]
Are the empty IIFEs present also in non-uglified JS? My first guess would be that there are CoffeeScript files that are empty or only has Sprockets requires.

**Comment by jcuenod** [comment]
There are some but surely this is not useful behaviour?

**Comment by lautis** [comment]
CoffeeScript wraps all files to a function that is invoked immediately. This prevents variable declarations from multiple files from interfering with each other when the files are concatenated (which is what Rails asset pipeline is doing). Sure, those empty functions could be removed in minification process, but UglifyJS isn't currently able to perform such optimisation.

**Comment by jcuenod** [comment]
Okay, so the solution is delete empty (auto-generated) files?

**Comment by lautis** [comment]
Yes, that should at least remove some of the functions. They don't really hurt you much anyway. Repetitive code should compress well.
