### ISSUE TITLE
compression is stumbling on javascript regular expression

### ISSUE THREAD

**Issue by dsaronin** [lautis/uglifier#84]
During the uglifier compression of the Google Polymer 1.0 javascript, it appears that uglifier is stumbling on the compression of the following code:
```
var rx = {
  comments: /\/\*[^*]*\*+([^\/*][^*]*\*+)*\//gim,
  port: /@import[^;]*;/gim,
  customProp: /(?:^|[\s;])--[^;{]*?:[^{};]*?;/gim,
  mixinProp: /(?:^|[\s;])--[^;{]*?:[^{;]*?{[^}]*?};?/gim,
  mixinApply: /@apply[\s]*\([^)]*?\)[\s]*;/gim,
  varApply: /[^;:]*?:[^;]*var[^;]*;/gim,
  keyframesRule: /^@[^\s]*keyframes/
};
```
In particular, within the second line, the stumble occurs after "+([^\".
Examining the resultant javascript with Chrome Developer's console, the code is showing up as:
```
var rx = {
comments: /\/\*[^*]*\*+([^\
	function doResolve(fn, onFulfilled, onRejected) {
```
That last line is from a different javascript file. The remaining 1800 lines from the Polymer javascript file are no longer present.

Uncompressed in development mode, of course, everything works fine.

I am using uglifier 2.7.1 with Ruby 2.2.1 in Rails 4.2.1.

It appears that uglifier has intruded within the regular expression and is considering the "/*" (within the larger regex) as the start of a comment, when it is actually not. Perhaps that is because comments are being stripped out BEFORE compression using non-lexical aware logic?

**Comment by dsaronin** [comment]
As a work-around:
I changed the order within the [....] to "[^*\/]" (essentially reversing the order of the slash-asterisk), and the uglifier compression proceeds without stumbling. So I'm fairly sure there's an error in the comment-removal logic.

**Comment by lautis** [comment]
The example you've given seems to minify without any issues on my setup. What ExecJS runtime/Uglifier version are you using? Where can I find the polymer.js file you're using?

The comment preservation/removal should be aware of JavaScript syntax. If there's an error, it is likely in UglifyJS2 that Uglifier uses to do the actual minification.

**Comment by dsaronin** [comment]
You can get the code for Polymer here: https://www.polymer-project.org/1.0/docs/start/getting-the-code.html 
Execjs: 2.5.2
Uglifier: 2.7.1

**Comment by lautis** [comment]
I tried running Uglifier on webcomponents.js, which contains the highlighted regex. The resulting file is valid and the regex is left untouched. If you'd like me to look further, it'd help to have a minimal app/script that reproduces this issue.

**Comment by dsaronin** [comment]
Thank you for looking into it. The issue occurs after pushing up the code to heroku and heroku is running the uglifier & compression gems (which I assume are the versions Iisted) prior to creating the execution slug. At this point, my simple-minded work-around works, so at least I can proceed with my development.
