### ISSUE TITLE
Update from 2.7.1 to 2.7.2 broke scripts

### ISSUE THREAD

**Issue by brunoluigi** [lautis/uglifier#87]
Don't know what happened but the my scripts uglified with 2.7.2 breaks while everything works fine with the 2.7.1 =/

I know this issue report is not very helpful right now but I'll update it with more info as soon as I can =)

**Comment by lautis** [comment]
@brunoluigi, have you managed to find anything on this? I'd guess that there could be a regression with UglifyJS update.

**Comment by toncid** [comment]
@brunoluigi Are you using AngularJS? Uglifier seems to misinterpret something in there...

**Comment by brunoluigi** [comment]
Yep, we're using AngularJS here =)

**Comment by toncid** [comment]
@lautis Thoughts?

**Comment by lautis** [comment]
Some more information about the breakages, Angular setup and Uglifier setup would be helpful. 

My first guess would be to look at function argument name mangling. Do you have it enabled (it's by default)? If so are you using [ng-annotate](https://github.com/olov/ng-annotate) or `@ngInject` to deal with dependency injection when minifying? This isn't very specific to the changes between 2.7.1 and 2.7.2 though :/

As UglifyJS 2.5.0 was released few days ago, it might be worth trying if that would fix the issues.
