### ISSUE TITLE
Error while trying to minify JS (with Rails)

### ISSUE THREAD

**Issue by andreynering** [lautis/uglifier#89]
This is a cross post from https://github.com/rails/sprockets/issues/187

This is the output message from the Rails task (`rake assets:precompile`): https://gist.githubusercontent.com/andreynering/123b60cb81e3a1c97dab/raw/bf7bad49c719e90231e6eafb91879d9ba25a58e3/output.txt

Unfortunately, I don't know how to reproduce it. But I think it should work, because the non-minified JS run without problems on both Chrome and Firefox.

**Comment by tabaliov** [comment]
Yep same problem here.

**Comment by andreynering** [comment]
I have a doubt: Is uglifier prepared to minify ES6?

Em sáb, 12 de dez de 2015 06:32, tabaliov <notifications@github.com>
escreveu:

**Comment by tabaliov** [comment]
Error i got was because of accidental ES6. i had functionName : (){}  instead of functionName: functon(){} no JS error in chrome but unable to compile.

**Comment by lautis** [comment]
ES6 would explain this. UglifyJS doesn't support ES6 syntax at least yet.

**Comment by andreynering** [comment]
Closing. See https://github.com/rails/sprockets/issues/187#issuecomment-164411210
