### ISSUE TITLE
new UglifyJS2 version for better error messages

### ISSUE THREAD

**Issue by Tenari** [lautis/uglifier#91]
https://github.com/mishoo/UglifyJS2/pull/535
As described there, UglifyJS2 has some new features, like listing the filename where ParseErrors occur, which I would be happy to have pulled into this gem.

**Comment by lautis** [comment]
Uglifier uses UglifyJS2. This particular patch is be included, but let's see if there's something to be done to map filename to UglifyJS2.

Typically that shouldn't matter much since when used together with Sprockets the original filename might be missing anyway.
